In [1]:
#Syntax:  varname=numpy.diag(ndarray,k)

In [2]:
import numpy as np
a=np.arange(9).reshape(3,3)
print("Matrix-A")
print(a)
print("Shape of Matrix-A=",a.shape)
print("Dim=",a.ndim)

Matrix-A
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Shape of Matrix-A= (3, 3)
Dim= 2


In [3]:
#Get the Priciple Diagnol Elements
pd=np.diag(a,0)
print("Principle Diag={}  Type={}".format(pd,type(pd)))

Principle Diag=[0 4 8]  Type=<class 'numpy.ndarray'>


In [4]:
#Get the Lower Principle Diagnol Elements
print("Matrix-A")
print(a)
pd=np.diag(a,-1)
print("Principle Diag={}  Type={}".format(pd,type(pd)))

Matrix-A
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Principle Diag=[3 7]  Type=<class 'numpy.ndarray'>


In [5]:
#Get the Above Principle Diagnol Elements
print("Matrix-A")
print(a)
pd=np.diag(a,k=1)
print("Principle Diag={}  Type={}".format(pd,type(pd)))

Matrix-A
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Principle Diag=[1 5]  Type=<class 'numpy.ndarray'>


In [6]:
import numpy as np
a=np.arange(16).reshape(4,4)
print("Matrix-A")
print(a)
print("Shape of Matrix-A=",a.shape)
print("Dim=",a.ndim)
pd=np.diag(a,0)
print("Principle Diag={}  Type={}".format(pd,type(pd)))

Matrix-A
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Shape of Matrix-A= (4, 4)
Dim= 2
Principle Diag=[ 0  5 10 15]  Type=<class 'numpy.ndarray'>
