In [1]:
#=>Syntax: varname=numpy.identity(N,dtype)

In [2]:
#Create an Identity Matrix With 2D
import numpy as np
a=np.identity(2)
print("Content of a\n{}  type of a={}".format(a,type(a)))
print("Dim of a={}".format(a.ndim)) 

Content of a
[[1. 0.]
 [0. 1.]]  type of a=<class 'numpy.ndarray'>
Dim of a=2


In [3]:
#Create an Identity Matrix With 2D
import numpy as np
a=np.identity(2,int)
print("Content of a\n{}  type of a={}".format(a,type(a)))
print("Dim of a={}".format(a.ndim)) 

Content of a
[[1 0]
 [0 1]]  type of a=<class 'numpy.ndarray'>
Dim of a=2


In [4]:
#Create an Identity Matrix With 3D
import numpy as np
a=np.identity(3,int)
print("Content of a\n{}  type of a={}".format(a,type(a)))
print("Dim of a={}".format(a.ndim))

Content of a
[[1 0 0]
 [0 1 0]
 [0 0 1]]  type of a=<class 'numpy.ndarray'>
Dim of a=2


In [5]:
#Create an Identity Matrix With 3D
import numpy as np
a=np.identity(4,int)
print("Content of a\n{}  type of a={}".format(a,type(a)))
print("Dim of a={}".format(a.ndim))

Content of a
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]  type of a=<class 'numpy.ndarray'>
Dim of a=2


In [6]:
#Create an Identity Matrix With 3D
import numpy as np
a=np.identity(6,int)
print("Content of a\n{}  type of a={}".format(a,type(a)))
print("Dim of a={}".format(a.ndim))

Content of a
[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]  type of a=<class 'numpy.ndarray'>
Dim of a=2
