In [1]:
#Syntax:  varname=numpy.full(shape, fill_value,dtype)

In [3]:
#Create an object of ndarray with 6 Entries as 3
import numpy as np
a=np.full(6,3)
print("Content of a={}  Type of a={}".format(a,type(a)))
print("Dim of a={}".format(a.ndim))

Content of a=[3 3 3 3 3 3]  Type of a=<class 'numpy.ndarray'>
Dim of a=1


In [4]:
#Create an object of ndarray with 6 Entries as 3
import numpy as np
a=np.full(6,3,float)
print("Content of a={}  Type of a={}".format(a,type(a)))
print("Dim of a={}".format(a.ndim))

Content of a=[3. 3. 3. 3. 3. 3.]  Type of a=<class 'numpy.ndarray'>
Dim of a=1


In [5]:
#Create an object of ndarray with 6 Entries as 3
import numpy as np
a=np.full(shape=6,fill_value=3,dtype=float)
print("Content of a={}  Type of a={}".format(a,type(a)))
print("Dim of a={}".format(a.ndim))

Content of a=[3. 3. 3. 3. 3. 3.]  Type of a=<class 'numpy.ndarray'>
Dim of a=1


In [11]:
#Create an object of ndarray with 6 Entries as 9 with 2D
import numpy as np
a=np.full(fill_value=9,shape=(3,2))
print("Content of a=\n{}  Type of a={}".format(a,type(a)))
print("Dim of a={}".format(a.ndim))

Content of a=
[[9 9]
 [9 9]
 [9 9]]  Type of a=<class 'numpy.ndarray'>
Dim of a=2


In [1]:
#Create an object of ndarray with 12 Entries as 8 with 3D
import numpy as np
a=np.full(fill_value=8,shape=(2,3,2))
print("Content of a=\n{}  Type of a={}".format(a,type(a)))
print("Dim of a={}".format(a.ndim))

Content of a=
[[[8 8]
  [8 8]
  [8 8]]

 [[8 8]
  [8 8]
  [8 8]]]  Type of a=<class 'numpy.ndarray'>
Dim of a=3
