In [3]:
#Creating an Object of ndarray by using array()
import numpy as np
a=10
print("Content of a={} Type a={}".format(a,type(a)))
a1=np.array(a)
print("Content of a={} Type a={}".format(a,type(a)))
print("Dimension ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndaaray={}".format(a1.size))

Content of a=10 Type a=<class 'int'>
Content of a=10 Type a=<class 'int'>
Dimension ndarray=0
Shape of ndarray=()
Size of ndaaray=1


In [4]:
#Creating an Object of ndarray by using array()
import numpy as np
a=10.25
print("Content of a={} Type a={}".format(a,type(a)))
a1=np.array(a)
print("Content of a={} Type a={}".format(a,type(a)))
print("Dimension ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndaaray={}".format(a1.size))

Content of a=10.25 Type a=<class 'float'>
Content of a=10.25 Type a=<class 'float'>
Dimension ndarray=0
Shape of ndarray=()
Size of ndaaray=1


In [5]:
#Creating an Object of ndarray by using array()
import numpy as np
a=2+3j
print("Content of a={} Type a={}".format(a,type(a)))
a1=np.array(a)
print("Content of a={} Type a={}".format(a,type(a)))
print("Dimension ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndaaray={}".format(a1.size))

Content of a=(2+3j) Type a=<class 'complex'>
Content of a=(2+3j) Type a=<class 'complex'>
Dimension ndarray=0
Shape of ndarray=()
Size of ndaaray=1


In [6]:
#Creating an Object of ndarray by using array()
import numpy as np
a="PYTHON"
print("Content of a={} Type a={}".format(a,type(a)))
a1=np.array(a)
print("Content of a={} Type a={}".format(a,type(a)))
print("Dimension ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndaaray={}".format(a1.size))

Content of a=PYTHON Type a=<class 'str'>
Content of a=PYTHON Type a=<class 'str'>
Dimension ndarray=0
Shape of ndarray=()
Size of ndaaray=1


In [7]:
#Creating an Object of ndarray by using array()
import numpy as np
a=range(10,0,-2)
print("Content of a={} Type a={}".format(a,type(a)))
a1=np.array(a)
print("Content of a={} Type a={}".format(a,type(a)))
print("Dimension ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndaaray={}".format(a1.size))

Content of a=range(10, 0, -2) Type a=<class 'range'>
Content of a=range(10, 0, -2) Type a=<class 'range'>
Dimension ndarray=1
Shape of ndarray=(5,)
Size of ndaaray=5


In [16]:
#Creating an Object of ndarray by using array()
import numpy as np
a=range(0,9)
print("Content of a={} Type a={}".format(a,type(a)))
a1=np.array(a)
print("Content of a={} Type a={}".format(a,type(a)))
print("Dimension ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndaaray={}".format(a1.size))

Content of a=range(0, 9) Type a=<class 'range'>
Content of a=range(0, 9) Type a=<class 'range'>
Dimension ndarray=1
Shape of ndarray=(9,)
Size of ndaaray=9


In [17]:
#Re-shape of ndarray Object--by using shape attribute
a1.shape=(3,3)
print("Content of a1\n{} Type a={}".format(a1,type(a1)))
print("Dimension ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndaaray={}".format(a1.size))

Content of a1
[[0 1 2]
 [3 4 5]
 [6 7 8]] Type a=<class 'numpy.ndarray'>
Dimension ndarray=2
Shape of ndarray=(3, 3)
Size of ndaaray=9


In [18]:
#Creating an Object of ndarray by using array()
import numpy as np
a=range(0,16)
print("Content of a={} Type a={}".format(a,type(a)))
a1=np.array(a)
a1.shape=(4,4)
print("Content of a1\n{} Type a={}".format(a1,type(a1)))
print("Dimension ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndaaray={}".format(a1.size))

Content of a=range(0, 16) Type a=<class 'range'>
Content of a1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] Type a=<class 'numpy.ndarray'>
Dimension ndarray=2
Shape of ndarray=(4, 4)
Size of ndaaray=16


In [19]:
#Creating an Object of ndarray by using array()
import numpy as np
a=range(0,16)
print("Content of a={} Type a={}".format(a,type(a)))
a1=np.array(a)
a1.shape=(2,4,2)
print("Content of a1\n{} Type a1={}".format(a1,type(a1)))
print("Dimension ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndaaray={}".format(a1.size))

Content of a=range(0, 16) Type a=<class 'range'>
Content of a1
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]] Type a1=<class 'numpy.ndarray'>
Dimension ndarray=3
Shape of ndarray=(2, 4, 2)
Size of ndaaray=16


In [21]:
#Creating an Object of ndarray by using array()
import numpy as np
a=range(0,16)
print("Content of a={} Type a={}".format(a,type(a)))
a1=np.array(a)
a1.shape=(2,2,2,2)
print("Content of a1\n{} Type a1{}".format(a1,type(a1)))
print("Dimension ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndaaray={}".format(a1.size))

Content of a=range(0, 16) Type a=<class 'range'>
Content of a1
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]] Type a1<class 'numpy.ndarray'>
Dimension ndarray=4
Shape of ndarray=(2, 2, 2, 2)
Size of ndaaray=16


In [22]:
#Creating an Object of ndarray by using array()
import numpy as np
a=range(24)
print("Content of a={} Type a={}".format(a,type(a)))
a1=np.array(a)
a1.shape=(6,4)
print("Content of a1\n{} Type a1{}".format(a1,type(a1)))
print("Dimension ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndaaray={}".format(a1.size))

Content of a=range(0, 24) Type a=<class 'range'>
Content of a1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] Type a1<class 'numpy.ndarray'>
Dimension ndarray=2
Shape of ndarray=(6, 4)
Size of ndaaray=24


In [23]:
#Creating an Object of ndarray by using array()
import numpy as np
a=range(24)
print("Content of a={} Type a={}".format(a,type(a)))
a1=np.array(a)
a1.shape=(6,4)
print("Content of a1\n{} Type a1{}".format(a1,type(a1)))
print("Dimension ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndaaray={}".format(a1.size))
print("Data type Element of ndarray={}".format(a1.dtype))

Content of a=range(0, 24) Type a=<class 'range'>
Content of a1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] Type a1<class 'numpy.ndarray'>
Dimension ndarray=2
Shape of ndarray=(6, 4)
Size of ndaaray=24
Data type Element of ndarray=int64


In [30]:
#Creating an Object of ndarray by using array()
import numpy as np
lst=[10,20,30,40,50,60,70,80]
print("Content of a={} Type a={}".format(lst,type(lst)))
a1=np.array(lst)
print("Content of a1\n{} Type a1{}".format(a1,type(a1)))
print("Dimension ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndaaray={}".format(a1.size))
print("Data type Element of ndarray={}".format(a1.dtype))

Content of a=[10, 20, 30, 40, 50, 60, 70, 80] Type a=<class 'list'>
Content of a1
[10 20 30 40 50 60 70 80] Type a1<class 'numpy.ndarray'>
Dimension ndarray=1
Shape of ndarray=(8,)
Size of ndaaray=8
Data type Element of ndarray=int64


In [29]:
#Creating an Object of ndarray by using array()
import numpy as np
lst=[10,20,30,40,50,60,70,80]
print("Content of a={} Type a={}".format(lst,type(lst)))
a1=np.array(lst,float).reshape(4,2)
print("Content of a1\n{} Type a1{}".format(a1,type(a1)))
print("Dimension ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndaaray={}".format(a1.size))
print("Data type Element of ndarray={}".format(a1.dtype))

Content of a=[10, 20, 30, 40, 50, 60, 70, 80] Type a=<class 'list'>
Content of a1
[[10. 20.]
 [30. 40.]
 [50. 60.]
 [70. 80.]] Type a1<class 'numpy.ndarray'>
Dimension ndarray=2
Shape of ndarray=(4, 2)
Size of ndaaray=8
Data type Element of ndarray=float64


In [31]:
#Creating an Object of ndarray by using array()
import numpy as np
lst=[[10,20],[30,40],[50,60],[70,80]]
print("Content of a={} Type a={}".format(lst,type(lst)))
a1=np.array(lst,float).reshape(4,2)
print("Content of a1\n{} Type a1{}".format(a1,type(a1)))
print("Dimension ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndaaray={}".format(a1.size))
print("Data type Element of ndarray={}".format(a1.dtype))

Content of a=[[10, 20], [30, 40], [50, 60], [70, 80]] Type a=<class 'list'>
Content of a1
[[10. 20.]
 [30. 40.]
 [50. 60.]
 [70. 80.]] Type a1<class 'numpy.ndarray'>
Dimension ndarray=2
Shape of ndarray=(4, 2)
Size of ndaaray=8
Data type Element of ndarray=float64


In [33]:
#Creating an Object of ndarray by using array()
import numpy as np
lst=[[[10,20],[30,40]],[[50,60],[70,80]]]
print("Content of a={} Type a={}".format(lst,type(lst)))
a1=np.array(lst,float)
print("Content of a1\n{} Type a1{}".format(a1,type(a1)))
print("Dimension ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndaaray={}".format(a1.size))
print("Data type Element of ndarray={}".format(a1.dtype))


Content of a=[[[10, 20], [30, 40]], [[50, 60], [70, 80]]] Type a=<class 'list'>
Content of a1
[[[10. 20.]
  [30. 40.]]

 [[50. 60.]
  [70. 80.]]] Type a1<class 'numpy.ndarray'>
Dimension ndarray=3
Shape of ndarray=(2, 2, 2)
Size of ndaaray=8
Data type Element of ndarray=float64


In [34]:
#Creating an Object of ndarray by using array()
import numpy as np
lst=(([10,20],[30,40]),([50,60],[70,80]))
print("Content of a={} Type a={}".format(lst,type(lst)))
a1=np.array(lst,float)
print("Content of a1\n{} Type a1{}".format(a1,type(a1)))
print("Dimension ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndaaray={}".format(a1.size))
print("Data type Element of ndarray={}".format(a1.dtype))

Content of a=(([10, 20], [30, 40]), ([50, 60], [70, 80])) Type a=<class 'tuple'>
Content of a1
[[[10. 20.]
  [30. 40.]]

 [[50. 60.]
  [70. 80.]]] Type a1<class 'numpy.ndarray'>
Dimension ndarray=3
Shape of ndarray=(2, 2, 2)
Size of ndaaray=8
Data type Element of ndarray=float64


In [39]:
#Creating an Object of ndarray by using array()
import numpy as np
lst={10,20,30,40,50,60,70,80,90}
print("Content of a={} Type a={}".format(lst,type(lst)))
a1=np.array(lst)
print("Content of a1{} Type a1{}".format(a1,type(a1)))
print("Dimension ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndaaray={}".format(a1.size))
print("Data type Element of ndarray={}".format(a1.dtype))

Content of a={70, 40, 10, 80, 50, 20, 90, 60, 30} Type a=<class 'set'>
Content of a1{70, 40, 10, 80, 50, 20, 90, 60, 30} Type a1<class 'numpy.ndarray'>
Dimension ndarray=0
Shape of ndarray=()
Size of ndaaray=1
Data type Element of ndarray=object


In [40]:
#Creating an Object of ndarray by using array()
import numpy as np
lst={1:"PYTHON",2:"C++",3:"JAVA",4:"C"}
print("Content of a={} Type a={}".format(lst,type(lst)))
a1=np.array(lst)
print("Content of a1{} Type a1{}".format(a1,type(a1)))
print("Dimension ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndaaray={}".format(a1.size))
print("Data type Element of ndarray={}".format(a1.dtype))

Content of a={1: 'PYTHON', 2: 'C++', 3: 'JAVA', 4: 'C'} Type a=<class 'dict'>
Content of a1{1: 'PYTHON', 2: 'C++', 3: 'JAVA', 4: 'C'} Type a1<class 'numpy.ndarray'>
Dimension ndarray=0
Shape of ndarray=()
Size of ndaaray=1
Data type Element of ndarray=object


In [43]:
#Creating an Object of ndarray by using array()
import numpy as np
lst=None
print("Content of a={} Type a={}".format(lst,type(lst)))
a1=np.array(lst)
print("Content of a1={} Type a1{}".format(a1,type(a1)))
print("Dimension ndarray={}".format(a1.ndim))
print("Shape of ndarray={}".format(a1.shape))
print("Size of ndaaray={}".format(a1.size))
print("Data type Element of ndarray={}".format(a1.dtype))

Content of a=None Type a=<class 'NoneType'>
Content of a1=None Type a1<class 'numpy.ndarray'>
Dimension ndarray=0
Shape of ndarray=()
Size of ndaaray=1
Data type Element of ndarray=object
