In [1]:
#varname=numpy.vstack( (ndarrayobj1,ndarrayobj2) )    

In [2]:
import numpy as np
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Matrix-A")
print(a)
print("Shape of Matrix-A=",a.shape)
b=np.array([[15,25,45],[55,35,65]])
print("Matrix-B")
print(b)
print("Shape of Matrix-B=",b.shape)

Matrix-A
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Shape of Matrix-A= (3, 3)
Matrix-B
[[15 25 45]
 [55 35 65]]
Shape of Matrix-B= (2, 3)


In [3]:
#Perform Vertical Stacking (Consider the Number of Cols)
c=np.vstack((a,b))
print("Matrix-C")
print(c)
print("Shape of Matrix-C=",c.shape)

Matrix-C
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 25 45]
 [55 35 65]]
Shape of Matrix-C= (5, 3)


In [4]:
#Perform Vertical Stacking (Consider the Number of Cols)
c=np.vstack((b,a))
print("Matrix-C")
print(c)
print("Shape of Matrix-C=",c.shape)

Matrix-C
[[15 25 45]
 [55 35 65]
 [10 20 30]
 [40 50 60]
 [70 80 90]]
Shape of Matrix-C= (5, 3)
