In [1]:
#rand()---> this function generates random sample(s) between 0.0 to 1.0
#varname=numpy.random.rand()
#varname=numpy.random.rand(value)
#varname=numpy.random.rand(rows, cols)
#varname=numpy.random.rand(no. of matrices, rows, cols)

In [3]:
from numpy import random as r
val=r.rand()
print("Random Sample={}  type={}".format(val,type(val)))

Random Sample=0.5846339779579769  type=<class 'float'>


In [4]:
val=r.rand()
print("Random Sample={}  type={}".format(val,type(val)))

Random Sample=0.555974682334561  type=<class 'float'>


In [7]:
#generate 5 random sample values for uniform distribution
val=r.rand(5)
print("Random Sample={}  \ntype={}".format(val,type(val)))

Random Sample=[0.81994406 0.5409258  0.37640977 0.76932667 0.71203906]  
type=<class 'numpy.ndarray'>


In [8]:
#generate 10 random sample values for uniform distribution
val=r.rand(10)
print("Random Sample={}  \ntype={}".format(val,type(val)))

Random Sample=[0.79356773 0.35650924 0.62627589 0.64429005 0.33145879 0.88776523
 0.73137007 0.95520948 0.90028863 0.54271501]  
type=<class 'numpy.ndarray'>


In [10]:
#generate 2D random sample values for uniform distribution with 3 rows and 3 clos
val=r.rand(3,3)
print("Random Sample=\n{}  \ntype={}".format(val,type(val)))

Random Sample=
[[0.87708796 0.08703361 0.21018787]
 [0.60880245 0.41190251 0.00402507]
 [0.8170165  0.85707774 0.21218011]]  
type=<class 'numpy.ndarray'>


In [11]:
#generate 2D random sample values for uniform distribution with 3 rows and 2 clos
val=r.rand(3,2)
print("Random Sample=\n{}  \ntype={}".format(val,type(val)))

Random Sample=
[[0.32417976 0.86047143]
 [0.7007885  0.22345528]
 [0.28773854 0.93062673]]  
type=<class 'numpy.ndarray'>


In [12]:
#generate 3D random sample values for uniform distribution with 2 matrices ,3 rows and 2 clos
val=r.rand(2,3,2)
print("Random Sample=\n{}  \ntype={}".format(val,type(val)))

Random Sample=
[[[0.64465682 0.17330786]
  [0.11586026 0.34152178]
  [0.62868822 0.77976071]]

 [[0.51297354 0.25791084]
  [0.74003945 0.13739043]
  [0.50921723 0.21998285]]]  
type=<class 'numpy.ndarray'>


In [16]:
val.shape=(12,)
print(val)

[0.64465682 0.17330786 0.11586026 0.34152178 0.62868822 0.77976071
 0.51297354 0.25791084 0.74003945 0.13739043 0.50921723 0.21998285]


In [17]:
val.shape


(12,)

In [18]:
val.ndim

1

In [19]:
val=val.reshape(3,4)
print(val)

[[0.64465682 0.17330786 0.11586026 0.34152178]
 [0.62868822 0.77976071 0.51297354 0.25791084]
 [0.74003945 0.13739043 0.50921723 0.21998285]]


In [20]:
val.shape

(3, 4)

In [21]:
val.ndim

2

In [23]:
val.shape=(12,)
print(val)

[0.64465682 0.17330786 0.11586026 0.34152178 0.62868822 0.77976071
 0.51297354 0.25791084 0.74003945 0.13739043 0.50921723 0.21998285]


In [24]:
for v in val:
    print(v)

0.644656824727078
0.1733078586169008
0.11586025616577666
0.3415217823176886
0.6286882214647036
0.7797607103223607
0.512973537205919
0.25791083722600694
0.7400394496437099
0.13739043076466806
0.5092172334338664
0.2199828464864262


In [25]:
for v in val:
    print("%0.2f" %v)

0.64
0.17
0.12
0.34
0.63
0.78
0.51
0.26
0.74
0.14
0.51
0.22


In [26]:
for v in val:
    print("{}".format(round(v,2)))

0.64
0.17
0.12
0.34
0.63
0.78
0.51
0.26
0.74
0.14
0.51
0.22
