In [3]:
#Code for Building  a Matrix with dim of 2 with All entries as 0
import numpy as np
lst=[0,0,0,0]
a=np.array(lst).reshape(2,2)
print("Zerox Matrix")
print(a)
print("Dim od a=",a.ndim)

Zerox Matrix
[[0 0]
 [0 0]]
Dim od a= 2


In [4]:
#Code for Building  a Matrix with dim of 2 with All entries as 0
import numpy as np
lst=[[0,0,0],[0,0,0],[0,0,0]]
a=np.array(lst)
print("Zerox Matrix")
print(a)
print("Dim od a=",a.ndim)

Zerox Matrix
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Dim od a= 2


In [6]:
#Create a object of ndarray with 6 zeros
import numpy as np
a=np.zeros(6)
print("Content of a={}  Type of a={}".format(a,type(a)))
print("Dim of a={}",a.ndim)

Content of a=[0. 0. 0. 0. 0. 0.]  Type of a=<class 'numpy.ndarray'>
Dim of a={} 1


In [7]:
#Create a object of ndarray with 6 zeros
import numpy as np
a=np.zeros(6,dtype=int)
print("Content of a={}  Type of a={}".format(a,type(a)))
print("Dim of a={}",a.ndim)

Content of a=[0 0 0 0 0 0]  Type of a=<class 'numpy.ndarray'>
Dim of a={} 1


In [9]:
#Create an object of ndarray with Dim 2 of 9 Elements as Zeros
import numpy as np
a=np.zeros((3,3))
print("Content of a=\n{}  Type of a={}".format(a,type(a)))
print("Dim of a={}",a.ndim)

Content of a=
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]  Type of a=<class 'numpy.ndarray'>
Dim of a={} 2


In [11]:
#Create an object of ndarray with Dim 2 of 9 Elements as Zeros
import numpy as np
a=np.zeros((3,3),dtype=int)
print("Content of a=\n{}  Type of a={}".format(a,type(a)))
print("Dim of a={}",a.ndim)

Content of a=
[[0 0 0]
 [0 0 0]
 [0 0 0]]  Type of a=<class 'numpy.ndarray'>
Dim of a={} 2


In [12]:
#Create an object of ndarray with Dim 3 of 12 Elements as Zeros
import numpy as np
a=np.zeros((2,3,2),dtype=int)
print("Content of a=\n{}  Type of a={}".format(a,type(a)))
print("Dim of a={}",a.ndim)

Content of a=
[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]  Type of a=<class 'numpy.ndarray'>
Dim of a={} 3


In [2]:
import numpy as np
a= np.zeros((2,2),dtype=int)
print(a)

[[0 0]
 [0 0]]


In [7]:
import numpy as np
a= np.arange(1,5).reshape(2,2)
print(a)


[[1 2]
 [3 4]]
