In [1]:
#syntax-1: numpy.random.randint(value)

In [3]:
import numpy.random as r
val=r.randint(10)
print("Random value={}  Type={}".format(val,type(val)))

Random value=5  Type=<class 'int'>


In [4]:
val=r.randint(10)
print("Random value={}  Type={}".format(val,type(val)))

Random value=1  Type=<class 'int'>


In [5]:
val=r.randint(100)
print("Random value={}  Type={}".format(val,type(val)))

Random value=59  Type=<class 'int'>


In [6]:
val=r.randint(1000)
print("Random value={}  Type={}".format(val,type(val)))

Random value=620  Type=<class 'int'>


In [7]:
#generate 5 Random values with above syntax
for i in range(1,6):
    val=r.randint(100)
    print("Random value={}  Type={}".format(val,type(val)))

Random value=3  Type=<class 'int'>
Random value=72  Type=<class 'int'>
Random value=29  Type=<class 'int'>
Random value=26  Type=<class 'int'>
Random value=55  Type=<class 'int'>


In [8]:
#syntax-2 : varname=numpay.random.randint(low,high)

In [12]:
import numpy as np
val=np.random.randint(1000,10000)
print("Random value={}  Type={}".format(val,type(val)))

Random value=5714  Type=<class 'int'>


In [13]:
import numpy as np
val=np.random.randint(10000,100000)
print("Random value={}  Type={}".format(val,type(val)))

Random value=19628  Type=<class 'int'>


In [16]:
import numpy as np
val=np.random.randint(10000,100000)
print("G-{}".format(val))

G-44038


In [17]:
import numpy as np
val=np.random.randint(10000,100000)
print("G-{}".format(val))

G-70143


In [18]:
import numpy as np
for i in range(1,6):
    val=np.random.randint(10000,100000)
    print("G-{}".format(val))

G-58867
G-87636
G-90903
G-91096
G-25521


In [19]:
#syntax-3: varname=numpy.random.randint(low,hight,size)

In [21]:
import numpy as np
val = np.random.randint(100,200,5)
print("Random vals={}  type={}".format(val,type(val)))
print("Dim of val={}  Shape={}".format(val.ndim,val.shape))

Random vals=[124 167 123 141 141]  type=<class 'numpy.ndarray'>
Dim of val=1  Shape=(5,)


In [22]:
import numpy as np
val = np.random.randint(1000,2000,10)
print("Random vals={}  type={}".format(val,type(val)))
print("Dim of val={}  Shape={}".format(val.ndim,val.shape))

Random vals=[1432 1768 1838 1572 1487 1637 1361 1480 1524 1143]  type=<class 'numpy.ndarray'>
Dim of val=1  Shape=(10,)


In [24]:
import numpy as np
val = np.random.randint(100,200,(2,2))
print("Random vals=\n{}  type={}".format(val,type(val)))
print("Dim of val={}  Shape={}".format(val.ndim,val.shape))

Random vals=
[[140 118]
 [120 156]]  type=<class 'numpy.ndarray'>
Dim of val=2  Shape=(2, 2)


In [25]:
import numpy as np
val = np.random.randint(1000,2000,(3,4))
print("Random vals=\n{}  type={}".format(val,type(val)))
print("Dim of val={}  Shape={}".format(val.ndim,val.shape))

Random vals=
[[1894 1324 1890 1759]
 [1289 1293 1851 1858]
 [1778 1764 1359 1109]]  type=<class 'numpy.ndarray'>
Dim of val=2  Shape=(3, 4)


In [26]:
print("Number of Rows=",val.shape[0])
print("Number of Clos=",val.shape[1])

Number of Rows= 3
Number of Clos= 4


In [27]:
import numpy as np
val = np.random.randint(1000,2000,(2,3,3))
print("Random vals=\n{}  type={}".format(val,type(val)))
print("Dim of val={}  Shape={}".format(val.ndim,val.shape))

Random vals=
[[[1771 1538 1881]
  [1447 1151 1162]
  [1080 1697 1793]]

 [[1344 1197 1129]
  [1557 1183 1201]
  [1272 1129 1621]]]  type=<class 'numpy.ndarray'>
Dim of val=3  Shape=(2, 3, 3)


In [28]:
print("Number of Marices=",val.shape[0])
print("Number of Rows=",val.shape[1])
print("Number of Clos=",val.shape[2])

Number of Marices= 2
Number of Rows= 3
Number of Clos= 3
