In [1]:
#Syntax:  varname=numpy.ones(shape,dtype)

In [2]:
#Create an object of ndarray with 6 Ones
import numpy as np
a=np.ones(6)
print("Content of a={}  Type of a={}".format(a,type(a)))
print("Dim of a={}".format(a.ndim))

Content of a=[1. 1. 1. 1. 1. 1.]  Type of a=<class 'numpy.ndarray'>
Dim of a=1


In [3]:
#Create an object of ndarray with 6 Ones
import numpy as np
a=np.ones(6,dtype=int)
print("Content of a={}  Type of a={}".format(a,type(a)))
print("Dim of a={}".format(a.ndim))

Content of a=[1 1 1 1 1 1]  Type of a=<class 'numpy.ndarray'>
Dim of a=1


In [9]:
#Create an object of ndarray with 9 Ones as 2D
import numpy as np
a=np.ones((3,3))
print("Content of a=\n{}  Type of a={}".format(a,type(a)))
print("Dim of a={}".format(a.ndim))

Content of a=
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]  Type of a=<class 'numpy.ndarray'>
Dim of a=2


In [10]:
#Create an object of ndarray with 9 Ones as 2D
import numpy as np
a=np.ones((3,3),int)
print("Content of a=\n{}  Type of a={}".format(a,type(a)))
print("Dim of a={}".format(a.ndim))

Content of a=
[[1 1 1]
 [1 1 1]
 [1 1 1]]  Type of a=<class 'numpy.ndarray'>
Dim of a=2


In [11]:
#Create an object of ndarray with 18 Ones as 3D
import numpy as np
a=np.ones((2,3,3),int)
print("Content of a=\n{}  Type of a={}".format(a,type(a)))
print("Dim of a={}".format(a.ndim))

Content of a=
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]  Type of a=<class 'numpy.ndarray'>
Dim of a=3
