In [1]:
#varname=numpy.hstack( (ndarrayobj1,ndarrayobj2) )

In [4]:
import numpy as np
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Matrix-A")
print(a)
print("Shape of Matrix-A=",a.shape)
b=np.array([[15,25],[45,55],[35,65]])
print("Matrix-B")
print(b)
print("Shape of Matrix-B=",b.shape)

Matrix-A
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Shape of Matrix-A= (3, 3)
Matrix-B
[[15 25]
 [45 55]
 [35 65]]
Shape of Matrix-B= (3, 2)


In [5]:
#Perform Horizontal Stacking(Consider the Number of Rows)
c=np.hstack((a,b))
print("Matrix-C")
print(c)
print("Shape of Matrix-C=",c.shape)

Matrix-C
[[10 20 30 15 25]
 [40 50 60 45 55]
 [70 80 90 35 65]]
Shape of Matrix-C= (3, 5)


In [7]:
#Perform Horizontal Stacking(Consider the Number of Rows)
d=np.hstack((b,a))
print("Matrix-D")
print(d)
print("Shape of Matrix-D=",d.shape)

Matrix-D
[[15 25 10 20 30]
 [45 55 40 50 60]
 [35 65 70 80 90]]
Shape of Matrix-D= (3, 5)


In [9]:
import numpy as np
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print("Matrix-A")
print(a)
print("Shape of Matrix-A=",a.shape)
b=np.array([[15,25,45],[55,35,65]])
print("Matrix-B")
print(b)
print("Shape of Matrix-B=",b.shape)
c=np.hstack((a,b))

Matrix-A
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Shape of Matrix-A= (3, 3)
Matrix-B
[[15 25 45]
 [55 35 65]]
Shape of Matrix-B= (2, 3)


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2